name: Windows CI

on:
  push:
  pull_request:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        shell: pwsh
        run: |
          cargo build --release
      - name: Smoke test (push/pull)
        shell: pwsh
        run: |
          ./scripts/smoke-windows.ps1 -Release
